---
- hosts: kvm_host
  vars_files:
    - vars/config.yml
    - vars/extra.yml

  tasks:
    - include_tasks: tasks/kvm_host/mk_files-dir.yml
    - include_tasks: tasks/kvm_host/install-pkg.yml
    - include_tasks: tasks/kvm_host/setup-selinux.yml
    - include_tasks: tasks/kvm_host/setup-firewalld.yml
    - include_tasks: tasks/kvm_host/setup-dnsmasq.yml
    - include_tasks: tasks/kvm_host/setup-libvirtd.yml
    - include_tasks: tasks/kvm_host/setup-nginx.yml
    - include_tasks: tasks/kvm_host/setup-ocp-install-config.yml
    - include_tasks: tasks/kvm_host/install-bootstrap.yml
    - include_tasks: tasks/kvm_host/install-master.yml
    - include_tasks: tasks/kvm_host/install-worker.yml
    - include_tasks: tasks/kvm_host/wait-for-complete.yml
