# Remove this yml file before closing the PR: this is just a playbook to rapidly iterate
---
- hosts: base
  gather_facts: yes
  vars_files:
    - vars/config.yml
    - vars/vm_setting.yml
    - vars/download.yml

  tasks:
    - include_tasks: tasks/base/mk_files-dir.yml
    - include_tasks: tasks/base/mk_dnsmasq-conf.yml
    - include_tasks: tasks/base/mk_libvirtd-conf.yml
    - include_tasks: tasks/base/get_materials.yml

- hosts: kvm_host
  gather_facts: yes
  vars_files:
    - vars/config.yml
    - vars/vm_setting.yml
    - vars/download.yml

  tasks:
    - include_tasks: tasks/kvm_host/mk_files-dir.yml
    - include_tasks: tasks/kvm_host/install-pkg.yml
    - include_tasks: tasks/kvm_host/setup-selinux.yml
    - include_tasks: tasks/kvm_host/setup-firewalld.yml
    - include_tasks: tasks/kvm_host/setup-dnsmasq.yml
    - include_tasks: tasks/kvm_host/setup-libvirtd.yml
    - include_tasks: tasks/kvm_host/install-storage.yml

    # NOTE: we do not include the helm chart installation here, as this test-playbook only tests the NFS server bits.
    # As we do not instantiate the control plane yet, there is no OCP cluster to run helm against
