---
- name: install libvirt, dnsmasq, nginx and related packages
  dnf:
    name:
      - libvirt-client
      - libvirt
      - qemu-kvm
      - virt-install
      - guestfs-tools
      - dnsmasq
      - nginx
      - python3-lxml
      - python3-libselinux
      - python3-policycoreutils
      - tar
      - unzip
    state: latest

- name: install ngxinx-mod-stream for RHEL9.0+
  dnf:
    name:
      - nginx-mod-stream
    state: latest
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version | int >= 9
