---
- name: install libvirt, dnsmasq, nginx and related packages
  dnf:
    name:
      - libvirt-client
      - libvirt
      - qemu-kvm
      - virt-install
      - dnsmasq
      - nginx
      - python3-lxml
      - python3-libselinux
      - python3-policycoreutils
      - tar
      - unzip
    state: latest

- name: install guestfs-tools and ngxinx-mod-stream for RHEL9.0+
  dnf:
    name:
      - guestfs-tools
      - nginx-mod-stream
    state: latest
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version | int >= 9

- name: install guestfs-tools(libguestfs-tools-c) for RHEL8.0+
  dnf:
    name:
      - libguestfs-tools-c
    state: latest
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version | int <= 9
