---
- name: make /root/bin dir
  file:
    path: /root/bin
    state: directory

- name: check old bare-metal dir
  stat:
    path: "{{ files.kvm }}/bare-metal"
  register: chk_file

- name: remove old bare-metal dir
  file:
    path: "{{ files.kvm }}/bare-metal"
    state: absent
  when: chk_file.stat.exists == true

- name: make bare-metal dir
  file:
    path: "{{ files.kvm }}/bare-metal"
    state: directory

- name: send install-config.yaml to kvm host
  copy:
    src:  "{{ files.base }}/conf/install-config.yaml"
    dest: "{{ files.kvm }}/bare-metal"

- name: send openshift installer
  unarchive:
    src: "{{ files.base }}/clients/{{ config.openshift_installer }}"
    dest: /root/bin
    exclude: README.md

- name: send openshift clients
  unarchive:
    src: "{{ files.base }}/clients/{{ config.openshift_client }}"
    dest: /root/bin
    exclude: README.md

- name: create ignition-configs
  command: "/root/bin/openshift-install create ignition-configs --dir={{ files.kvm }}/bare-metal"

- name: copy ign files
  copy:
    src:  "{{ files.kvm }}/bare-metal/{{ item }}"
    dest: /usr/share/nginx/html/openshift/coreos/ignitions
    selevel: s0
    serole: object_r
    setype: httpd_sys_content_t
    seuser: system_u
    mode: 0644
    remote_src: true
  with_items:
    - bootstrap.ign
    - master.ign
    - worker.ign

